### ISSUE TITLE
TsdMetricsFactory.Builder should fail on build() if requirements are not met.

### ISSUE THREAD

**Issue by ddimensia** [ArpNetworking/metrics#10]
If the TsdMetricsFactory.Builder isn't supplied a clusterName or serviceName it still succeeds in returning a TsdMetricsFactory object even though the metrics object(s) it creates will never succeed in outputting metrics.  The build() method should fail if required fields are not specified before hand.

**Comment by vjkoskela** [comment]
This is a result of the no-exception policy in this project. We modeled it after libraries like Logback which even on construction failure do not throw an exception. I'm happy to reevaluate this policy but at the moment this is working as designed.

**Comment by ddimensia** [comment]
Maybe a better solution would be to have a builder hierarchy where you can't actually call build() until all required fields are set.  Effectively have setClusterName().setServiceName() return a 'buildable' builder that can only be accessed through those methods.

**Comment by ddimensia** [comment]
I guess the other option would be to have these as constructor arguments to the Builder.

**Comment by vjkoskela** [comment]
Thanks for the suggestions! I've seen a project (need to find its name) that code generated such a builder hierarchy so it was effectively compile-time checking of required fields. Definitely an option to be considered if it can be integrated easily.

I'm not a fan of the required settings as constructor arguments because this can easily lead to long constructors and without named arguments (as it is now in Java at least) this can become a real source of errors. 

Given these alternatives have their complications we need to evaluate them against revising the policy. We typically start with a blanket policy and then adjust it as needed. This case would seem reasonable to allow exceptions in the builders. Maybe controlled via some mechanism so they can be silenced or enabled. I imagine your tests would have caught this problem, so having exceptions on explicitly in test would have worked too (while still off in production).

**Comment by ddimensia** [comment]
How would you expect to a test to verify this?  Can you provide an example where you could have caught that a field you didn't know was required was set?

**Comment by vjkoskela** [comment]
Sorry, let me clarify; if we conditionally enabled exceptions (e.g. for testing purposes) then a test which executed the metrics path of your code (hopefully you have such a test) would have thrown an exception instead of accepting the partial configuration. 

Taking this one step further,  a test that asserts expected metrics generation would also catch this error (possibly even without exception throwing enabled). I believe the JTier team at Groupon has something like this.

When a required field is not set you get an instance of the factory which simply logs warnings and doesn't output metrics (because it was not configured completely). So the test outlined above should have caught this immediately without knowing anything really about the metrics themselves (because nothing would have been written versus something).

**Comment by ddimensia** [comment]
I think I was looking for a concrete example of the second testing approach you mentioned.  I did a search for JTier and Groupon and didn't come up with anything except for something related to NodeJS, have a feeling that's not what you meant.

**Comment by vjkoskela** [comment]
JTier is an internal Groupon project at the moment (as far as I know). I do believe they plan to open source it, but I don't believe it has reached a level of maturity required for that. I mentioned it because you know the engineers working on it, including [brianm](https://github.com/brianm), perhaps they can show you some of what is being done to test metrics integration.
